# Generated by Django 5.0.4 on 2024-05-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_payment_amount_remove_payment_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
